version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "vigo"
    labels:
      - "dependabot"
      - "github-actions"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[gha] - upgrade github action dependencies"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "vigo"
    assignees:
      - "vigo"
    labels:
      - "dependabot"
      - "gomod"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[gomod] - upgrade go dependencies"
      include: "scope"
